export movies = [ { 
title: "", 
genre: "", 
ageRating: 10, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 10, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 10, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 16, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "",
genre: "", 
ageRating: 16, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 18, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 16, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 16, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 18, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 18, synopsis: "", 
trailer: "" 
},
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 16, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 18, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
} 
];

